# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: who.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='who.proto',
  package='who',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\twho.proto\x12\x03who\"\x1b\n\x0b\x43\x61llRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\t\"\x18\n\tCallReply\x12\x0b\n\x03out\x18\x01 \x01(\t21\n\x03Who\x12*\n\x04\x43\x61ll\x12\x10.who.CallRequest\x1a\x0e.who.CallReply\"\x00\x62\x06proto3')
)




_CALLREQUEST = _descriptor.Descriptor(
  name='CallRequest',
  full_name='who.CallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='who.CallRequest.args', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=45,
)


_CALLREPLY = _descriptor.Descriptor(
  name='CallReply',
  full_name='who.CallReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='out', full_name='who.CallReply.out', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['CallRequest'] = _CALLREQUEST
DESCRIPTOR.message_types_by_name['CallReply'] = _CALLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALLREQUEST,
  __module__ = 'who_pb2'
  # @@protoc_insertion_point(class_scope:who.CallRequest)
  ))
_sym_db.RegisterMessage(CallRequest)

CallReply = _reflection.GeneratedProtocolMessageType('CallReply', (_message.Message,), dict(
  DESCRIPTOR = _CALLREPLY,
  __module__ = 'who_pb2'
  # @@protoc_insertion_point(class_scope:who.CallReply)
  ))
_sym_db.RegisterMessage(CallReply)



_WHO = _descriptor.ServiceDescriptor(
  name='Who',
  full_name='who.Who',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=73,
  serialized_end=122,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='who.Who.Call',
    index=0,
    containing_service=None,
    input_type=_CALLREQUEST,
    output_type=_CALLREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WHO)

DESCRIPTOR.services_by_name['Who'] = _WHO

# @@protoc_insertion_point(module_scope)
