# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import who_pb2 as who__pb2


class WhoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Call = channel.unary_unary(
        '/who.Who/Call',
        request_serializer=who__pb2.CallRequest.SerializeToString,
        response_deserializer=who__pb2.CallReply.FromString,
        )


class WhoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Call(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WhoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Call': grpc.unary_unary_rpc_method_handler(
          servicer.Call,
          request_deserializer=who__pb2.CallRequest.FromString,
          response_serializer=who__pb2.CallReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'who.Who', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
